exp_name: "debug"
root_dir: "/root/workspace/activity_estimation/"
pretrain: True
model_path: "/root/workspace/activity_estimation/models/ViT-B-16.pt"
visual_dim: 2304
text_dim: 2048
emb_dim: 2048
clip_length: 10
train:
  epochs: 50
  val_freq: 5
  batch_size: 1
  num_workers: 0
  shuffle: True
  clip_gradient: 20
  optimizer: 
    type: "adamw"
    lr: 5.e-6
    momentum: 0.9
    weight_decay: 0.2
  lr_scheduler: 
    type: "cosine"
    lr_warmup_step: 5
    lr_decay_step: 15
    lr_decay_factor: 0.1
output_dir: "/root/workspace/activity_estimation/output"