exp_name: "testrun_30epochs_bsz20_lr5e-5_vsfusion_3layer"
root_dir: "/root/workspace/activity_estimation/"
wandb: True
pretrain: True
model_path: "/root/workspace/activity_estimation/models/ViT-B-16.pt"
visual_dim: 2304
text_dim: 2048
emb_dim: 2048
vs_fusion: False
fusion_layers: 3
clip_length: 10
train:
  epochs: 30
  val_freq: 10
  batch_size: 1
  gradient_acc: 20
  num_workers: 8
  shuffle: True
  optimizer: 
    type: "adamw"
    lr: 5.e-5
    momentum: 0.9
    weight_decay: 0.2
  lr_scheduler: 
    type: "exp"
    lr_warmup_epoch: 5
    lr_decay_epoch: 15
    lr_decay_factor: 1.e-3
output_dir: "/root/workspace/activity_estimation/output"